export const words = [
    { word: '会う', pronunciation: 'あう', translation: 'to meet' },
    { word: '開く', pronunciation: 'あく', translation: 'to open' },
    { word: '遊ぶ', pronunciation: 'あそぶ', translation: 'to play' },
    { word: '新しい', pronunciation: 'あたらしい', translation: 'new' },
    { word: '雨', pronunciation: 'あめ', translation: 'rain' },
    { word: '夏', pronunciation: 'なつ', translation: 'summer' },
    { word: '友達', pronunciation: 'ともだち', translation: 'friend' },
    { word: '日', pronunciation: 'ひ', translation: 'day' },
    { word: '時間', pronunciation: 'じかん', translation: 'time' },
    { word: '学校', pronunciation: 'がっこう', translation: 'school' },
    { word: '先生', pronunciation: 'せんせい', translation: 'teacher' },
    { word: '食べる', pronunciation: 'たべる', translation: 'to eat' },
    { word: '飲む', pronunciation: 'のむ', translation: 'to drink' },
    { word: '話す', pronunciation: 'はなす', translation: 'to speak' },
    { word: '猫', pronunciation: 'ねこ', translation: 'cat' },
    { word: '犬', pronunciation: 'いぬ', translation: 'dog' },
    { word: '大きい', pronunciation: 'おおきい', translation: 'big' },
    { word: '小さい', pronunciation: 'ちいさい', translation: 'small' },
    { word: '高い', pronunciation: 'たかい', translation: 'expensive' },
    { word: '安い', pronunciation: 'やすい', translation: 'cheap' },
    { word: '美しい', pronunciation: 'うつくしい', translation: 'beautiful' },
    { word: '楽しい', pronunciation: 'たのしい', translation: 'fun' },
    { word: '寒い', pronunciation: 'さむい', translation: 'cold' },
    { word: '暑い', pronunciation: 'あつい', translation: 'hot (weather)' },
    { word: '早い', pronunciation: 'はやい', translation: 'fast' },
    { word: '遅い', pronunciation: 'おそい', translation: 'slow' },
    { word: '強い', pronunciation: 'つよい', translation: 'strong' },
    { word: '弱い', pronunciation: 'よわい', translation: 'weak' },
    { word: '赤い', pronunciation: 'あかい', translation: 'red' },
    { word: '青い', pronunciation: 'あおい', translation: 'blue' },
    { word: '白い', pronunciation: 'しろい', translation: 'white' },
    { word: '黒い', pronunciation: 'くろい', translation: 'black' },
    { word: '黄色い', pronunciation: 'きいろい', translation: 'yellow' },
    { word: '緑', pronunciation: 'みどり', translation: 'green' },
    { word: '紫', pronunciation: 'むらさき', translation: 'purple' },
    { word: '空', pronunciation: 'そら', translation: 'sky' },
    { word: '海', pronunciation: 'うみ', translation: 'sea' },
    { word: '山', pronunciation: 'やま', translation: 'mountain' },
    { word: '川', pronunciation: 'かわ', translation: 'river' },
    { word: '森', pronunciation: 'もり', translation: 'forest' },
    { word: '花', pronunciation: 'はな', translation: 'flower' },
    { word: '木', pronunciation: 'き', translation: 'tree' },
    { word: '魚', pronunciation: 'さかな', translation: 'fish' },
    { word: '鳥', pronunciation: 'とり', translation: 'bird' },
    { word: '車', pronunciation: 'くるま', translation: 'car' },
    { word: '電車', pronunciation: 'でんしゃ', translation: 'train' },
    { word: '自転車', pronunciation: 'じてんしゃ', translation: 'bicycle' },
    { word: '飛行機', pronunciation: 'ひこうき', translation: 'airplane' },
    { word: '道', pronunciation: 'みち', translation: 'road' },
    { word: '家', pronunciation: 'いえ', translation: 'house' },
    { word: '部屋', pronunciation: 'へや', translation: 'room' },
    { word: '本', pronunciation: 'ほん', translation: 'book' },
    { word: '手紙', pronunciation: 'てがみ', translation: 'letter' },
    { word: '電話', pronunciation: 'でんわ', translation: 'telephone' },
    { word: '音楽', pronunciation: 'おんがく', translation: 'music' },
    { word: '映画', pronunciation: 'えいが', translation: 'movie' },
    { word: 'テレビ', pronunciation: 'てれび', translation: 'TV' },
    { word: 'ラジオ', pronunciation: 'らじお', translation: 'radio' },
    { word: '新聞', pronunciation: 'しんぶん', translation: 'newspaper' },
    { word: '雑誌', pronunciation: 'ざっし', translation: 'magazine' },
    { word: 'パソコン', pronunciation: 'ぱそこん', translation: 'personal computer' },
    { word: '仕事', pronunciation: 'しごと', translation: 'work, job' },
    { word: '会社', pronunciation: 'かいしゃ', translation: 'company' },
    { word: 'お金', pronunciation: 'おかね', translation: 'money' },
    { word: '料理', pronunciation: 'りょうり', translation: 'cooking, cuisine' },
    { word: '野菜', pronunciation: 'やさい', translation: 'vegetable' },
    { word: '果物', pronunciation: 'くだもの', translation: 'fruit' },
    { word: 'ご飯', pronunciation: 'ごはん', translation: 'cooked rice, meal' },
    { word: 'パン', pronunciation: 'ぱん', translation: 'bread' },
    { word: '水', pronunciation: 'みず', translation: 'water' },
    { word: 'お茶', pronunciation: 'おちゃ', translation: 'tea' },
    { word: 'コーヒー', pronunciation: 'こーひー', translation: 'coffee' },
    { word: '牛乳', pronunciation: 'ぎゅうにゅう', translation: 'milk' },
    { word: '肉', pronunciation: 'にく', translation: 'meat' },
    { word: 'ケーキ', pronunciation: 'けーき', translation: 'cake' },
    { word: '名前', pronunciation: 'なまえ', translation: 'name' },
    { word: '国', pronunciation: 'くに', translation: 'country' },
    { word: '町', pronunciation: 'まち', translation: 'town' },
    { word: '今日', pronunciation: 'きょう', translation: 'today' },
    { word: '明日', pronunciation: 'あした', translation: 'tomorrow' },
    { word: '昨日', pronunciation: 'きのう', translation: 'yesterday' },
    { word: '今週', pronunciation: 'こんしゅう', translation: 'this week' },
    { word: '来週', pronunciation: 'らいしゅう', translation: 'next week' },
    { word: '先週', pronunciation: 'せんしゅう', translation: 'last week' },
    { word: '今年', pronunciation: 'ことし', translation: 'this year' },
    { word: '来年', pronunciation: 'らいねん', translation: 'next year' },
    { word: '去年', pronunciation: 'きょねん', translation: 'last year' },
    { word: '朝', pronunciation: 'あさ', translation: 'morning' },
    { word: '昼', pronunciation: 'ひる', translation: 'daytime, noon' },
    { word: '夜', pronunciation: 'よる', translation: 'night' },
    { word: '晩', pronunciation: 'ばん', translation: 'evening' },
    { word: '時計', pronunciation: 'とけい', translation: 'clock, watch' },
    { word: 'カレンダー', pronunciation: 'かれんだー', translation: 'calendar' },
    { word: '月', pronunciation: 'つき', translation: 'moon, month' },
    { word: '星', pronunciation: 'ほし', translation: 'star' },
    { word: '太陽', pronunciation: 'たいよう', translation: 'sun' },
    { word: '雲', pronunciation: 'くも', translation: 'cloud' },
    { word: '風', pronunciation: 'かぜ', translation: 'wind' },
    { word: '雪', pronunciation: 'ゆき', translation: 'snow' },
    { word: '天気', pronunciation: 'てんき', translation: 'weather' },
    { word: '傘', pronunciation: 'かさ', translation: 'umbrella' },
    { word: '靴', pronunciation: 'くつ', translation: 'shoes' },
    { word: '服', pronunciation: 'ふく', translation: 'clothes' },
    { word: '帽子', pronunciation: 'ぼうし', translation: 'hat' },
    { word: '眼鏡', pronunciation: 'めがね', translation: 'glasses' },
    { word: 'バッグ', pronunciation: 'バッグ', translation: 'bag' },
    { word: '鍵', pronunciation: 'かぎ', translation: 'key' },
    { word: 'ドア', pronunciation: 'どあ', translation: 'door' },
    { word: '窓', pronunciation: 'まど', translation: 'window' },
    { word: '机', pronunciation: 'つくえ', translation: 'desk' },
    { word: '椅子', pronunciation: 'いす', translation: 'chair' },
    { word: 'ベッド', pronunciation: 'べっど', translation: 'bed' },
    { word: '部屋', pronunciation: 'へや', translation: 'room' },
    { word: 'トイレ', pronunciation: 'トイレ', translation: 'toilet' },
    { word: 'お風呂', pronunciation: 'おふろ', translation: 'bath' },
    { word: 'キッチン', pronunciation: 'キッチン', translation: 'kitchen' },
    { word: '冷蔵庫', pronunciation: 'れいぞうこ', translation: 'refrigerator' },
    { word: '洗濯機', pronunciation: 'せんたくき', translation: 'washing machine' },
    { word: '掃除機', pronunciation: 'そうじき', translation: 'vacuum cleaner' },
    { word: 'ご飯', pronunciation: 'ごはん', translation: 'meal, rice' },
    { word: 'パン', pronunciation: 'ぱん', translation: 'bread' },
    { word: '卵', pronunciation: 'たまご', translation: 'egg' },
    { word: '野菜', pronunciation: 'やさい', translation: 'vegetables' },
    { word: '肉', pronunciation: 'にく', translation: 'meat' },
    { word: '魚', pronunciation: 'さかな', translation: 'fish' },
    { word: '果物', pronunciation: 'くだもの', translation: 'fruit' },
    { word: 'お菓子', pronunciation: 'おかし', translation: 'sweets, snacks' },
    { word: '飲み物', pronunciation: 'のみもの', translation: 'drinks' }
  ];